name: cv_template
description: "A project to create a nice looking CV."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Used for the theme until Flutter fixes the theming mess.
  # For more information, see https://rydmike.com/flexcolorscheme/themesplayground-latest/
  auto_size_text: ^3.0.0
  firebase_core: ^2.30.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  pdf: ^3.10.8
  responsive_framework: ^1.4.0
  screenshot: ^2.3.0
  syntax_highlight: ^0.4.0
  timelines: ^0.1.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
